
library(tidyverse)
library(sf)
#library(inborutils)
library(rio)
library(tidyverse)
library(janitor)
library(readxl)
library(openxlsx) 
library(rio)
library(readr)
library(sampling)
library(misty)
library(haven)
library(labelled)
library(foreign)
library(srvyr)
library(survey)
library(reshape2)
library(sjlabelled)
library(ggplot2)
library(samplesize4surveys)

print("Se han leido las librerias")
